version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.develop
    image: tamplo_server_dev
    ports:
      - 4001:4001
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    container_name: server-tamplo-dev
