version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    image: ${DOCKER_IMAGE_NAME}
    ports:
      - ${API_PORT}:4000
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    container_name: ${DOCKER_CONTAINER_NAME}
