version: '2'

services:
  app:
    build: .
    image: tamplo_server
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    container_name: server-tamplo
  mongodb:
    image: mongo
    volumes:
      - tamplo-db:/data/db
    container_name: db-tamplo

volumes:
  tamplo-db:
